apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: argocd-test
  name: argocd-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: argocd-test
  labels:
    app: simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
      - image: docker.io/kostiscodefresh/gitops-simple-app:v2.0
        imagePullPolicy: Always
        name: webserver-simple
        ports:
        - containerPort: 8080
