apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: argocd-test
  labels:
    app: simple-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    app: trivial-go-web-app
  type: NodePort
